// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gravação EP Apaixonado Como Nunca - EscalaMusic",
  description: "Confirme sua presença na gravação do EP 'Apaixonado Como Nunca' - 09/10 às 15h na Prainha Natal. Sistema de confirmação e check-in para convidados.",
  keywords: "EscalaMusic, EP, Apaixonado Como Nunca, gravação, música, evento, Natal, confirmação presença",
  authors: [{ name: "EscalaMusic" }],
  creator: "EscalaMusic",
  publisher: "EscalaMusic",
  robots: "index, follow",
  openGraph: {
    title: "Gravação EP Apaixonado Como Nunca - EscalaMusic",
    description: "Confirme sua presença na gravação do EP 'Apaixonado Como Nunca' - 09/10 às 15h na Prainha Natal",
    type: "website",
    locale: "pt_BR",
    siteName: "EscalaMusic",
  },
  twitter: {
    card: "summary_large_image",
    title: "Gravação EP Apaixonado Como Nunca - EscalaMusic",
    description: "Confirme sua presença na gravação do EP 'Apaixonado Como Nunca' - 09/10 às 15h na Prainha Natal",
  },
  viewport: "width=device-width, initial-scale=1",
  themeColor: "#667eea",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}